version: "3.8"

services:
  server:
    container_name: server_nginx
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php
      - mysql
    networks:
      - rede
  php:
    container_name: php
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - rede
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: "teste"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: ""
      MYSQL_ROOT_PASSWORD: ""
    restart: always
    volumes:
      - ./docker/.dbdata:/var/lib/mysql
    networks:
      - rede
  npm:
    container_name: npm
    image: node:16-alpine
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes:
      - ./src:/var/www/html
    networks:
      - rede

networks:
  rede:
    driver: bridge